version: '3.1'

services:

  node:
    env_file:
      - ./.env
    container_name: ${INSTALLATION}_node
    build: ./docker/node
    tty: true
    volumes:
      - ./app:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
      # In case you want to use http-server for testing purposes
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"